name: EvergreenChat
version: 1.0.0
description: Evergreen's Chat System
author: KayaLambrex
main: ever.green.chat.Main
api-version: 1.17
depend: [DiscordSRV]
softdepend: [PlaceholderAPI]
commands:
   ch:
   chreload:
   chlist:
   chspy: