name: EvergreenChat
version: 26.6.2
author: KayaLambrex
main: ever.green.Chat
api-version: '1.20'
depend: [DiscordSRV]
softdepend: [PlaceholderAPI, GriefPrevention, PerchTags, mcMMO]

commands:
  evergreenchat:
    description: Core EvergreenChat command.
    aliases: [ech, em]
  messagechat:
    description: Send a chat message.
    permission: evergreen.chat.admin
  messageactionbar:
    description: Send an actionbar message.
    permission: evergreen.chat.admin
  messagebossbar:
    description: Send a bossbar message.
    permission: evergreen.chat.admin
  dismiss:
    description: Dismisses your active screen messages.
  customadvancements.suppress:
    description: Hides advancement notifications in chat
    default: false